# Generated by Django 3.0.6 on 2020-09-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_admin',
            field=models.TextField(default=False),
        ),
    ]
